<?php namespace design\bridge;

class BaiduCorp extends Corp
{
    public function __construct(Product $product)
    {
        parent::__construct($product);
    }

    public function makeMoney()
    {
        parent::makeMoney(); // TODO: Change the autogenerated stub
    }
}